version: 2.1
jobs:
  build:
    parameters:
      install-type:
        type: string
    docker:
      # The first image entry here will be used as the image for the parent container.
      - image: tools-ext-01.ccr.xdmod.org/xdmod-job_performance-10.0.0:rockylinux8-0.1
    environment:
      TERM: xterm
      COMPOSER_ALLOW_SUPERUSER: 1
      XDMOD_REALMS: 'jobs,storage,cloud'
      XDMOD_IS_CORE: yes
      XDMOD_INSTALL_DIR: /xdmod
      XDMOD_TEST_MODE: << parameters.install-type >>
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: ./tests/ci/setup.sh
      - run:
          name: Create Test Result Directories
          command: |
            mkdir -p shippable/testresults
            mkdir -p shippable/codecoverage
      - run:
          name: Run Bootstrap
          command: ./tests/integration_tests/bootstrap.sh
      - run:
          name: Run Integration Tests
          command: ./tests/integration_tests/integration_test.bash
      - run:
          name: Run Component Tests
          command: ./tests/component/runtests.sh
      - run:
          name: Summarize Jobs
          command: summarize_jobs.py -h > /dev/null
      - run:
          name: Index Archives
          command: indexarchives.py -h > /dev/null
      - run:
          name: Ingest Jobs
          command: ingest_jobscripts.py -d
      - run:
          name: Remove Currently Installed SUPREMM
          command: yum remove -y supremm
      - run:
          name: Install SUPREMM
          command: python3 setup.py install --user --prefix=
      - run:
          name: Pylint
          command: pylint-3 --errors-only supremm
      - run:
          name: Pytest
          command: pytest-3 --junitxml=shippable/testresults/testreport.xml --cov=supremm --cov-report xml:shippable/codecoverage/coverage.xml
      - run:
          name: Summarize Jobs
          command: /root/.local/bin/summarize_jobs.py -h > /dev/null
      - run:
          name: Index Archives
          command: /root/.local/bin/indexarchives.py -h > /dev/null
      - store_test_results:
          path: shippable/testresults
      - store_artifacts:
          path: shippable/codecoverage
      - store_artifacts:
          path: /var/log/xdmod

workflows:
  full-build:
    jobs:
      - build:
          matrix:
            parameters:
              install-type: ["fresh_install", "upgrade"]
